### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by jiatianluo** [ttlzfhy/D-DPCC#7]
I try to run the command "python test_owlii.py --log_name='aaa' --gpu=1 --frame_count=32 --results_dir='results' --tmp_dir='tmp' --dataset_dir='/home/zhaoxudong/Owlii_10bit'",but an err occurred,it said"permission denied:/PCGCv2_num_points.bin"，but I have given this file all the permissions,could you please tell me why and what should I do?Should me use "sudo"?

**Comment by ttlzfhy** [comment]
I haven't encountered this problem before, but PCGCv2_num_points.bin is generated in the ./tmp folder when testing. Maybe you can check if you have the writing permission in ./tmp and if all the files in ./PCGCv2 have permission?

**Comment by jiatianluo** [comment]
Thank you for your reply!Could you please tell me why I can not find the file which is called "tmp/PCGCv2.ply"?And,is your algorithm based on x86 architecture, my system is ARM architecture, can I run your code?

**Comment by ttlzfhy** [comment]
Seems that PCGCv2 files didn't run correctly. Can you share the whole error information?

**Comment by jiatianluo** [comment]
![4a0486fdb46f2fc0769db34fbc306fa](https://github.com/user-attachments/assets/7ed00e6f-6f6d-4ce2-85a8-df54a44c5daa)
ok，this is the whole error information.

**Comment by jiatianluo** [comment]
(d_dpcc) onx002@ubuntu:~/Downloads/D-DPCC-main$ python3 test_owlii.py --log_name='aaa' --gpu=0 --frame_count=32 --results_dir='results' --tmp_dir='tmp' --dataset_dir='/home/onx002/Downloads'
Using /home/onx002/.cache/torch_extensions/py38_cu114 as PyTorch extensions root...
Emitting ninja build file /home/onx002/.cache/torch_extensions/py38_cu114/torchac_backend/build.ninja...
Building extension module torchac_backend...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module torchac_backend...
PARAMETER ...
Namespace(channels=8, ckpt_dir='./ddpcc_ckpts', dataset_dir='/home/onx002/Downloads', frame_count=32, gpu='0', log_name='aaa', lossless_model='DDPCC_lossless_coder', model='DDPCC_geo', overwrite=False, pcgcv2_ckpt_dir='./pcgcv2_ckpts', results_dir='results', tmp_dir='tmp')
start testing sequence D-DPCC-main, rate point ./ddpcc_ckpts/r1.pth
f bpp     d1PSNR  d2PSNR
/lib64/ld-linux-x86-64.so.2: No such file or directory
/lib64/ld-linux-x86-64.so.2: No such file or directory
Traceback (most recent call last):
  File "test_owlii.py", line 177, in &lt;module&gt;
    bpp, d1psnr, d2psnr, f1 = test_one_frame(f1, pcgcv2_ckpt, os.path.join(tmp_dir,
  File "/home/onx002/Downloads/D-DPCC-main/PCGCv2/eval.py", line 126, in test_one_frame
    x_dec = coder.decode(rho=rho)
  File "/home/onx002/anaconda3/envs/d_dpcc/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/onx002/Downloads/D-DPCC-main/../PCGCv2/coder.py", line 96, in decode
    y_C = self.coordinate_coder.decode(postfix=postfix)
  File "/home/onx002/Downloads/D-DPCC-main/../PCGCv2/coder.py", line 33, in decode
    coords = read_ply_ascii_geo(self.ply_filename)
  File "/home/onx002/Downloads/D-DPCC-main/../PCGCv2/data_utils.py", line 21, in read_ply_ascii_geo
    files = open(filedir)
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/PCGCv2.ply'

If you need,this is the all words on terminal.

**Comment by ttlzfhy** [comment]
I'm afraid that's an environment problem, due to the ARM architecture. Maybe you can try to run trainer.py as it's dependent to PCGCv2, see if there's still this error and build a x86_64 platform docker image.

**Comment by ZHao-JRYan** [comment]
I encountered the same problem that 'jiatianluo' encountered.  My CPU is based on x86 architecture, and I have successfully run trainer.py. So I guess it isn‘t an environment problem? Could you please tell me why I can not find the file which is called "tmp/PCGCv2.ply"

**Comment by ttlzfhy** [comment]
Can you share the detailed error information? And I am afraid that ```FileNotFoundError: [Errno 2] No such file or directory: 'tmp/PCGCv2.ply'``` is due to limited permission of tmc3. You can try to solve it by ```chmod 777 ./GPCC/tmc3```

**Comment by ZHao-JRYan** [comment]
You are right, the reason why it can't run is due to  limited permission of tmc3. I have solved this problem. I appreciate a lot!
